<template>
  <div id="pcic-notice-print" class="notice-doc" v-if="data">
    <div class="notice-header">
      <h1>Republic of the Philippines</h1>
      <h2>Municipal Agriculture Office — Echague, Isabela</h2>
      <h3>NOTICE OF CLAIM — Philippine Crop Insurance Corporation (PCIC)</h3>
    </div>

    <section class="notice-section">
      <h4>Farmer Information</h4>
      <table class="notice-table">
        <tr><td class="lbl">Name</td><td>{{ data.farmer.name }}</td></tr>
        <tr><td class="lbl">RSBSA No.</td><td>{{ data.farmer.rsbsa_no || 'N/A' }}</td></tr>
        <tr><td class="lbl">Mobile</td><td>{{ data.farmer.mobile_number || 'N/A' }}</td></tr>
        <tr><td class="lbl">Address</td><td>{{ data.farmer.barangay }}, {{ data.farmer.city }}, {{ data.farmer.province }}</td></tr>
        <tr><td class="lbl">Sex / Birthdate</td><td>{{ data.farmer.sex || 'N/A' }} / {{ data.farmer.birthdate || 'N/A' }}</td></tr>
      </table>
    </section>

    <section class="notice-section">
      <h4>Farm Parcel</h4>
      <table class="notice-table">
        <tr><td class="lbl">Commodity</td><td>{{ data.plot.commodity || 'N/A' }}</td></tr>
        <tr><td class="lbl">Registered Area</td><td>{{ data.plot.size_ha }} ha</td></tr>
        <tr><td class="lbl">Barangay</td><td>{{ data.plot.location_brgy || data.farmer.barangay }}</td></tr>
        <tr><td class="lbl">Farm Type</td><td>{{ data.plot.farm_type || 'N/A' }}</td></tr>
      </table>
    </section>

    <section class="notice-section">
      <h4>Calamity &amp; Damage Details</h4>
      <table class="notice-table">
        <tr><td class="lbl">Calamity Type</td><td>{{ data.calamity.type }}</td></tr>
        <tr><td class="lbl">Calamity Name</td><td>{{ data.calamity.name }}</td></tr>
        <tr><td class="lbl">Date of Calamity</td><td>{{ data.calamity.date }}</td></tr>
        <tr><td class="lbl">Crop Stage</td><td>{{ data.calamity.crop_stage || 'N/A' }}</td></tr>
        <tr><td class="lbl">Damage Percentage</td><td>{{ data.calamity.damage_percentage }}%</td></tr>
        <tr><td class="lbl">Area Destroyed</td><td>{{ data.calamity.area_destroyed_ha }} ha</td></tr>
        <tr><td class="lbl">Estimated Value Lost</td><td>PHP {{ formatMoney(data.calamity.estimated_value_lost) }}</td></tr>
      </table>
    </section>

    <section class="notice-section" v-if="data.enrollment">
      <h4>PCIC Enrollment Reference</h4>
      <table class="notice-table">
        <tr><td class="lbl">Policy Reference</td><td>{{ data.enrollment.policy_reference || 'Pending' }}</td></tr>
        <tr><td class="lbl">Coverage Year</td><td>{{ data.enrollment.coverage_year }}</td></tr>
        <tr><td class="lbl">Crop Season</td><td>{{ data.enrollment.crop_season }}</td></tr>
        <tr><td class="lbl">Insured Area</td><td>{{ data.enrollment.insured_area_ha }} ha</td></tr>
      </table>
    </section>

    <section class="notice-section geo-photo">
      <div class="geo-block">
        <h4>Geographic Coordinates</h4>
        <p v-if="data.geo.latitude">Latitude: {{ Number(data.geo.latitude).toFixed(6) }}</p>
        <p v-if="data.geo.longitude">Longitude: {{ Number(data.geo.longitude).toFixed(6) }}</p>
        <p v-else class="muted">No GPS coordinates recorded.</p>
      </div>
      <div class="photo-block" v-if="data.photo_url">
        <h4>Photo Evidence</h4>
        <img :src="data.photo_url" alt="Damage evidence" class="evidence-photo" />
      </div>
    </section>

    <section class="notice-section">
      <h4>Audit Trail</h4>
      <table class="notice-table">
        <tr><td class="lbl">Field Technician</td><td>{{ data.audit.technician || 'N/A' }}</td></tr>
        <tr><td class="lbl">Barangay Verifier</td><td>{{ data.audit.verifier || 'N/A' }}</td></tr>
        <tr><td class="lbl">MAO Approver</td><td>{{ data.audit.approver || 'N/A' }}</td></tr>
        <tr><td class="lbl">Notice Filed By</td><td>{{ data.audit.notice_filer || 'N/A' }}</td></tr>
        <tr><td class="lbl">Status</td><td>{{ data.status }}</td></tr>
      </table>
    </section>

    <div class="sig-block">
      <div class="sig-line">
        <div class="sig-box"></div>
        <p>Municipal Agriculturist</p>
      </div>
      <div class="sig-line">
        <div class="sig-box"></div>
        <p>Farmer / Claimant</p>
      </div>
    </div>

    <p class="footer-note">Generated by AGRI-AKAP — MAO Echague Digital Claims System</p>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  data: any;
}>();

const formatMoney = (v: any) => {
  const n = Number(v);
  return isNaN(n) ? '0.00' : n.toLocaleString('en-PH', { minimumFractionDigits: 2 });
};
</script>

<style scoped>
.notice-doc {
  background: #fff;
  color: #111;
  padding: 24px;
  max-width: 800px;
  margin: 0 auto;
  font-family: 'Times New Roman', serif;
  font-size: 12pt;
}
.notice-header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #1a4731; padding-bottom: 12px; }
.notice-header h1 { font-size: 11pt; margin: 0; font-weight: normal; }
.notice-header h2 { font-size: 13pt; margin: 4px 0; color: #1a4731; }
.notice-header h3 { font-size: 12pt; margin: 8px 0 0; font-weight: bold; text-decoration: underline; }
.notice-section { margin-bottom: 16px; }
.notice-section h4 { font-size: 11pt; color: #1a4731; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin: 0 0 8px; }
.notice-table { width: 100%; border-collapse: collapse; }
.notice-table td { padding: 4px 8px; border: 1px solid #ddd; font-size: 10pt; }
.notice-table .lbl { width: 35%; font-weight: bold; background: #f8fafc; }
.geo-photo { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.evidence-photo { max-width: 100%; max-height: 200px; border: 1px solid #ccc; }
.sig-block { display: flex; justify-content: space-around; margin-top: 40px; }
.sig-line { text-align: center; }
.sig-box { width: 180px; border-bottom: 1px solid #000; height: 40px; margin-bottom: 4px; }
.footer-note { text-align: center; font-size: 8pt; color: #666; margin-top: 24px; }
.muted { color: #888; font-style: italic; }

@media print {
  .notice-doc { padding: 0; }
}
</style>
